fix some header include, these are not always in ffmpeg/ directory

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -628,12 +628,12 @@ if [ -n "$ffmpegdir" ]; then
 fi
 
 echolog "Checking for libavformat ..."
-check_lib ffmpeg/avformat.h av_register_all -lavformat || die "Error, can't find libavformat !"
 add_pkgconfig_deps libavformat
+check_lib avformat.h av_register_all -lavformat || die "Error, can't find libavformat !"
 
 echolog "Checking for libavcodec ..."
-check_lib ffmpeg/avcodec.h avcodec_register_all -lavcodec || die "Error, can't find libavcodec !"
 add_pkgconfig_deps libavcodec
+check_lib avcodec.h avcodec_register_all -lavcodec || die "Error, can't find libavcodec !"
 
 #################################################
 #   version
